rtp/src/ext.rs, str0m/examples/chat.rs, str0m/examples/http-post.rs, str0m/src/lib.rs, str0m/src/media/mod.rs, str0m/src/session.rs, str0m/src/session_sdp.rs
=> Enable feedback if negotiated in SDP

sdp/src/data.rs, str0m/src/media/codec.rs, str0m/src/media/mod.rs, str0m/src/session_sdp.rs
=> Fix problem in h264 matching

ice/src/agent.rs, ice/src/pair.rs, ice/tests/ice-lite-no-conn.rs
=> Fix connection never timing out for ice-lite

str0m/src/session.rs
Prior to this packet arriving on a repair stream that repaired a rid
did not get attribute correctly to the rid in question.
=> Correctly identify rid for repair streams

net/Cargo.toml, net/src/lib.rs, net/src/sha1.rs, net/src/stun.rs, rtp/Cargo.toml, rtp/src/srtp.rs
This makes a significant speed improvement on M1 Mac. Hopefully similar on x86.
=> asm feature for sha1

rtp/src/rtcp/twcc.rs
When a TWCC feedback report arrives so late that the packets it pertains
to are no longer in the TwccSendRecvRegister's queue we panic with an
assertion error.
For example, if the oldest packet in the queue has TWCC sequence number
1200 and we receive a feedback packet with a base sequence number
of 1199 an assert will trigger a panic.
=> Fix TWCC later report bug

str0m/src/media/register.rs
Previously we forced a move of `nack_check_from` in `RecvRegister` even
if we had a consecutive run of packets. Now we prioritise the
consecutive run of packets over forcing.
=> Always move forward on consecutive packet runs

rtp/src/rtcp/twcc.rs
The delta values in a TWCC report should accumulate from one packet
status to the next when iterating through them, this wasn't the case.
=> Fix TwccIter delta accumulation

src/rtp/id.rs, src/rtp/rtcp/mod.rs, src/rtp/rtcp/twcc.rs
Add a way to get a range of TWCC send records for BWE.
=> Add TwccSendRegister::send_records

src/media/event.rs, src/media/mline.rs, src/packet/buffer_tx.rs, src/packet/g7xx.rs, src/packet/h264.rs, src/packet/mod.rs, src/packet/opus.rs, src/packet/pacer.rs, src/packet/vp8.rs, src/packet/vp9.rs
Some simple code hygiene. We have duplicate enums with Audio/Video values. This merges them to one.
=> Merge types MediaKind and PacketKind

src/packet/pacer.rs
- Undo experimental padding logic
- Increase max padding packets limit
=> Improve pacer padding

src/packet/bwe/acked_bitrate_estimator.rs, src/packet/bwe/arrival_group.rs, src/packet/bwe/mod.rs, src/rtp/rtcp/twcc.rs, src/session.rs
Ports part of the, more robust, acked bitrate estimator from libWebRTC.
=> Robuster Acked Bitrate

README.md, examples/chat.rs, src/change/mod.rs, src/change/sdp.rs, src/dtls/mod.rs, src/dtls/ossl.rs, src/format.rs, src/ice/agent.rs, src/lib.rs, src/media/event.rs, src/media/inner.rs, src/media/mod.rs, src/rtp/ext.rs, src/rtp/header.rs, src/rtp/mod.rs, src/sdp/data.rs, src/sdp/parser.rs, src/session.rs
* Remove internal ExtMap type
* Rename Extensions -> ExtensionMap
* Improve API for ExtensionMap
=> Expose Extension and ExtensionMap in the API

src/format.rs, src/lib.rs, src/rtp/mtime.rs
fix typo in enable opus api
change frequence to frequency
=> spelling fixes

src/packet/pacer.rs, src/rtp/bandwidth.rs
Attempting to chase down the source of our lacklustre padding. This introduces a test that simulates realistic conditions for the pacer and ensure it's asking for the correct amount of padding.
=> Add a realistic pacer test

src/packet/h264.rs, src/rtp/header.rs
Fixes for h.264 discovered by sending from Windows usin Nvidia HVEC.
=> h.264 fixes

src/packet/mod.rs, src/packet/pacer.rs, src/session.rs
Get rid of PollOutcome and generate padding as part of handle_timeout
loop.
=> Simplify pacer further

src/packet/pacer.rs, src/rtp/header.rs, tests/rtp-mode.rs
=> make clippy happy

src/sdp/parser.rs
=> sdp: allow m-sections to have no c-line.

src/media/inner.rs, src/packet/buffer_tx.rs, src/packet/mod.rs, src/packet/ring.rs
This  brings the same performance improvements on padding generation as #171 , and also makes looking up by seq_no O(1)
=> Improved performance of buffer_tx lookups

src/packet/bwe/mod.rs
`e7705ab` accidentally introduced a hot loop by not restricting polling
when no valid hypothesis exists.
=> Fix BWE hot loop

src/sctp/dcep.rs
=> Change the DCEP ACK message type to 0x02

src/streams/send.rs
Just using a `usize` saves us the heap allocation of a VecDeque.
=> Remove VecDeque for padding

src/format.rs, src/ice/candidate.rs, src/rtp/ext.rs
We are converting to and from str0m constructs and it would be useful and avoid code duplication if we could pub and add the following.
=> pub some things

src/streams/send.rs
=> Set StreamTx::rtx_pt on poll_packet

src/packet/pacer.rs, src/streams/send.rs, src/streams/send_queue.rs
This fixes several issues that caused infinite run loop behaviour when BWE was used.
=> Various fixes

src/change/sdp.rs, src/streams/mod.rs, tests/unidirectional-r-create-media.rs
=> Fix StreamTx setup when remote side declared RecvOnly

src/streams/rtx_cache.rs, src/streams/send.rs
- Ensure we always generate padding
- Make more effort to find a spurious RTX packet
=> Padding tweaks

src/change/direct.rs, tests/repeated.rs
=> direct api expose rx by mid

src/media/mod.rs, src/rtp/id.rs
Based on discussion in #183 increase to 16 similar to libwebrtc.
We use numbers as mid and we did hit 100 in some scenarios so we need increase.
=> Increase size of Mid

src/streams/send.rs
Recent refactoring has meant that we lost queued at for Resends and
Padding, but at least now this feature will compile.
=> Make _internal_dont_use_log_stats feature compile

src/streams/send.rs, src/streams/send_queue.rs, tests/rtx-cache-0.rs
- Test for rtx-cache-0
- Leave packet in send_queue until sent
=> Fix RTX cache 0 take 2

src/lib.rs
Need access to the VideoOrientation enum to convert to and from with the rtp api.
=> Pub VideoOrientation

src/lib.rs, src/media/writer.rs
- Error on write() unknown RID
- writer() None if mid isnt sending direction
=> Writer improvements

src/media/mod.rs, src/session.rs, src/streams/mod.rs, src/streams/send.rs
- Encapsulation of blank packet sentinel value
- Set blank packet PT before first regular packet
=> Padding before first regular packet

src/streams/rtx_cache.rs, src/streams/send.rs
- rtx_cache: fixed size slots
- rtx_cache: use evict_in_batches and remove other way
=> rtx_cache optimizations

README.md, src/bwe.rs, src/change/direct.rs, src/change/mod.rs, src/lib.rs, src/media/writer.rs, src/rtp/header.rs, src/rtp/id.rs, src/stats.rs, src/streams/receive.rs, src/streams/send.rs
- Move BWE to bwe pub mod
- Doc fixes
=> Docs for 0.2.0

src/change/sdp.rs, src/ice/agent.rs, src/ice/candidate.rs, src/packet/vp8.rs, src/packet/vp9.rs
- ice: blank out ufrag on Candidate once added
- Clippy fixes
=> ice: blank out ufrag on Candidate once added

src/media/writer.rs, src/rtp/rtcp/sdes.rs, src/session.rs, src/streams/mod.rs, src/streams/receive.rs
- Fix changing SSRC in FF
- Fix bug in reading SDES from FF
=> FF compatibility fixes

src/streams/send.rs
`sum_since()` keeps re-evaluating the sum in the last second. Since `now` always move ahead we cannot precalculate the sum easily. Here I am updating it at 20 Hz which should be sufficient. I am getting a hit/miss ratio of 10 logging with println! which causes overhead so i expect it has greater impact with profiling
=> sender: re-evaluate rtx ratio every 50ms

src/streams/register.rs
- register: clear statuses on rollover + seq jump
- fix typo
=> fix missing nack reports

src/change/direct.rs, src/channel.rs, src/lib.rs, src/sctp/mod.rs, tests/data-channel-direct.rs
Not sure if I missed something here. Please check that it's sane.
=> Direct api add close for data channel

src/lib.rs
Creating new dtlscert takes time and is expensive, in a server scenario one might want to reuse the certs.
This change allow the user to create it's own cert and then clone it for new instances instead of str0m creating a new one on every configure.
If a user have not created a cert then the build will generate one.
=> Remove DtlsCert::new() on RtcConfig::new()

src/change/sdp.rs
The `change_ssrc` and `maybe_reset_rtx` already do logging. This
removes some extra logging that is already captured.
=> Simplify logging on SDP a=ssrc change

src/session.rs
I can reproduce this with Safari. Safari sometimes sends rtx probes before we discover the corresponding "main ssrc" (so we can't pick it up). If we don't send nacks there will never be an RTX active and the stream gets corrupted with minimal loss
=> receive: allow nacks so we discover rtx

src/packet/pacer.rs, src/rtp/mod.rs
Modulus 16 for SRTP.
Close #266
=> Up max blank padding size to 240

src/format.rs, src/packet/buffer_rx.rs, src/packet/mod.rs, src/packet/vp9.rs
This PR implements solution discussed in the issue #404.
=> VP9 SVC layers mapping

src/packet/buffer_rx.rs
Fixes depacketization issues on transient discontinuities explained
in #411
=> Depacketization cache based on sequence numbers

src/ice/agent.rs, src/ice/candidate.rs, src/io/stun.rs
Extracts the documentation changes out of https://github.com/algesten/str0m/pull/419 as they are not controversial and can be landed immediately.
=> Improve documentation of `ice` & `stun` module

src/streams/register_nack.rs
A very large seq jump would result in a very large amount of time spent evicting the same buffer entries multiple times.
=> nack register: fix handling big seq jumps

src/lib.rs, src/packet/buffer_rx.rs, src/packet/h264.rs, src/packet/mod.rs, src/packet/vp8.rs, src/packet/vp9.rs
- VP8/VP9 do not panic on underrun in parsing
- Fix sid out of bounds index bug
- h264 test fixes and refactoring
- Fix broken h264 test
=> Fix depack fuzz bugs

examples/http-post.rs
=> Fix broken http-post example

src/streams/send.rs
Without this padding and BWE do not work
=> Fix setting pt for padding

Cargo.lock, Cargo.toml
Improves data channels on lossy connections
=> Update sctp-protocol to 0.1.7

src/ice/agent.rs
As discussed in https://github.com/algesten/str0m/pull/476.
=> feat: remove min advance in `IceAgent::handle_timeout`

src/channel.rs
Previously `ChannelHandler` used the number of active channels to derive the next `ChannelId`. This resulted in two channels getting assigned the same `ChannelId` because the allocation didn't track which `ChannelId`s were free to be reused. For example, when two channels were created, allocating channel IDs 0 and 1, `ChannelId(0)` was freed and then a new channel was created, this new channel had an ID 1, which was already in use.
Start using a `usize` counter to allocate channel IDs, ensuring they're unique
=> Fix `ChannelId` allocation

Cargo.lock, Cargo.toml
Found a bug in sctp-proto: https://github.com/webrtc-rs/sctp-proto/issues/8
It's fixed so let's update.
=> Update sctp-proto for panic fix

src/lib.rs
`RtcConfig` no longer stores local ICE credentials by default, instead generating new credentials every time an `Rtc` instance is created with that config. Alternatively, the local credentials can be explicitly set to preserve previous behavior.
This fixes an API issue where the user may accidentally create multiple `Rtc` instances with the same credentials, causing potential STUN traffic misrouting.
=> Make `RtcConfig` local ICE creds optional

src/ice/agent.rs, src/ice/mod.rs
The new API discussed in https://github.com/algesten/str0m/pull/496. Opening here for further discussion as a draft. Will report back with results of experiment but the passing unit test is already giving me good vibes :)
=> feat: allow invalidating remote candidates

Cargo.lock, Cargo.toml
Another bump moving some logging from debug to trace in sctp crate
=> Bump sctp-proto to 0.2.2

src/ice/agent.rs
=> feat: make timing advance (Ta) configurable

src/crypto/ossl/cert.rs
Resolves https://github.com/algesten/str0m/issues/517
This simply uses a randomly generated 128-bit value as the serial instead. I don't have a strong opinion on the exact length, but thought this would make collisions with other certs basically impossible.
=> Change DTLS cert serial selection from sequential to random

src/lib.rs, src/session.rs, src/streams/mod.rs, src/util/mod.rs
This is by suggestion from @xnorpx.
=> Provide reason for Output::Timeout

src/_internal_test_exports/fuzz.rs, src/_internal_test_exports/rng.rs, src/media/event.rs, src/packet/buffer_rx.rs, src/rtp/ext.rs, src/rtp/mtime.rs, src/rtp/rtcp/sr.rs, src/streams/receive.rs, src/streams/send.rs
Also rename "nominator" to "numerator"
=> Make MediaTimes be unsigned, like Durations

CHANGELOG.md, Cargo.lock, Cargo.toml
- **Update changelog**
- **0.6.1**
=> Release 0.6.1

src/rtp/id.rs, src/streams/send.rs
Q8 in: https://srtp.sourceforge.net/historical/faq.html
=> Reduce the range of initial sequence number

CHANGELOG.md, Cargo.lock, Cargo.toml
- **Update changelog**
- **Bump deps**
- **0.6.3**
=> Release 0.6.3

src/ice/mod.rs
In #600, we fixed a bug that triggered a `panic` in `str0m` when certain arithmetic operations on an `Instant` failed. Only after merging did I think of an idea on how this can actually be unit-tested.
`Instant`s are represented in a platform-specific way, with some arbitrary point-in-time as a reference point. To simulate this, we attempt to subtract `Duration`s until we find this earliest point where a previous one can now longer be represented. We then attempt to use this point in time to run a `host - host` ICE handshake, ensuring that `str0m` handles the case gracefully where the provided `Instant` can no longer handle earlier points in time.
=> chore: add test for #598

src/io/stun.rs
Some of the logic around calculating padding for variable length attributes resulted in extra padding when none was necessary.
=> Fix incorrect padding in STUN attributes

src/sctp/mod.rs
=> Avoid overwriting acked SCTP association

src/ice/agent.rs, src/ice/candidate.rs, src/ice/mod.rs
=> Prefer relayed candidates with matching IP versions

src/rtp/rtcp/sdes.rs
=> Fix bug misparsing SDES

src/rtp/rtcp/sdes.rs
When calculating the SDES word size, the `SdesType::END` written in `write_to` isn't considered in the `word_size()` method, leading to an assertion when generating the rtcp fb.
This adds the missing byte and a test that checks all possible boundary conditions for a cname (1-255)
=> Fix off-by-one in SDES word size calculation

CHANGELOG.md, src/lib.rs
=> Add methods to configure STUN retransmission settings

CHANGELOG.md, src/channel.rs, src/sctp/mod.rs, tests/data-channel.rs
=> Channel::config() to get data channel config
