algesten/str0m

packet/src/buffer_tx.rs
rtp/src/ext.rs
rtp/src/header.rs
rtp/src/lib.rs
str0m/examples/chat.html
str0m/examples/chat.rs
str0m/src/lib.rs
str0m/src/media/mod.rs
str0m/tests/bidirectional.rs
str0m/tests/unidirectional.rs

This commit reintroduces a media::Writer as a builder pattern to allow for adding metadata to the data being sent. Rid, audio level, voice activity and video orientation are optional metadata.
Close #23

media: (re-)introduce a builder pattern for sending media

---

str0m/src/media/mod.rs
str0m/src/media/receiver.rs
str0m/src/media/sender.rs

It's wrong to not count m-lines that are not sending or receiving because what we want to count is also the total peer traffic.
If we exclude a track on a change of direction the byte counts would decrease as if there was a negative traffic, which does not make sense.
With this patch we simply avoid outputting stats related to sender / receiver sources with no traffic

fix how we avoid sending empty stats

---

str0m/examples/chat.rs
str0m/src/lib.rs
str0m/src/stats.rs

I wanted to add stats to the chat example, but I found it too aggressive to simply log out events every seconds, so I made the interval configurable.

Configurable stats interval

---

str0m/src/media/mline.rs
str0m/src/media/sender.rs
str0m/src/stats.rs

Before this commit we were calculating stats from latest RR received. Turns out browsers send RRs much more frequently especially in case of network problems (10+ per second). Downsampling to the latest every second looses a lot of information considering that each RR reports the fraction lost from the previous one.
With this patch we are averaging the values weighted against the amount of packet seen by the receiver, which makes much more sense in the case of a periodic update.

egress loss: average stats from intermediate receiver reports

---

packet/src/buffer_rx.rs
packet/src/h264.rs
packet/src/h265.rs
packet/src/lib.rs
packet/src/opus.rs
packet/src/vp8.rs
packet/src/vp9.rs
str0m/src/lib.rs
str0m/src/media/event.rs
str0m/src/media/mline.rs

Example use case: A user (of the lib) can decide to
- avoid packaging discardable frames to save bandwidth
- switch off VP8 layer 1 to save bandwidth
Internally str0m could use such information for an internal congestion control to compensate the overhead cause by answering Nacks

add Vp8 codec extra

---

Cargo.toml

was trying to compile on windows and saw this one
note that one need a windows version of perl like strawberry perl in the path to get openssl to compile

remove comment out duplicate

---

src/channel.rs
src/lib.rs
src/sctp/mod.rs

This change makes it so ChannelId is not longer the actual SCTP channel id, but rather mapped via an internal association lookup. The association can then be delayed until after the SCTP init.
Closes #91

Delay allocation of actual SCTP channel until after init

---

src/packet/bwe/arrival_group.rs
src/packet/bwe/mod.rs
src/packet/bwe/trendline_estimator.rs
src/session.rs

- Add limit on received packets in burst
- Order TWCC acked packets
- twcc arrival group: fix arrival and departure times
- Fix precision of last_remote_recv_time
- Set initial BWE bitrates correctly

Fix incorrect delay variations

---

src/lib.rs
src/media/inner.rs
src/media/mod.rs
src/packet/buffer_tx.rs
src/packet/g7xx.rs
src/packet/h264.rs
src/packet/mod.rs
src/packet/opus.rs
src/packet/pacer.rs
src/packet/vp8.rs
src/packet/vp9.rs
src/session.rs

This PR aims to reduce the number of QueueState calculations to see if we can improve the flamegraph of where code time is spent.
This splits QueueState into two halves, QueueState/QueueSnapshot and
the snapshot is used on the PacketizingBuffer level and QueueState on
the MediaInner level.  This is to avoid needing all knowledge about
what kind of data we're handling inside the PacketizingBuffer.
The more important change is adding an internal TotalQueue struct in
PacketizingBuffer that continuously keeps track of the total queue
duration in the buffer. This way we can avoid an expensive
recalculation on every MediaInner::queue_state() call.

Cheaper queue state

---

src/change/mod.rs
src/change/sdp.rs
src/format.rs
src/lib.rs
src/media/event.rs
src/media/inner.rs
src/media/mod.rs
src/packet/mod.rs
src/sdp/data.rs
src/sdp/mod.rs
src/sdp/parser.rs
src/session.rs
tests/bidirectional.rs
tests/unidirectional.rs

This splits out the codec configuration related structs from the sdp module, making it clearer what is about SDP parsing/serializing and what is generic config of the session.

Make PayloadParams, CodecSpec and Codec public API

---

src/packet/bwe/acked_bitrate_estimator.rs

This ports more of the code from libWebRTC, in particular it makes the
estimate more robust to momentary variance in the acked bitrate. This in
turn helps by not triggering significant drops in the estimated bitrate
due to the capping to the acked rate in rate control.
This seems to improve the estimate stability quite a bit, in particular we have fewer of these large drops in the estimate.
<details>
<summary>Before</summary>
</details>
<details>
<summary>After</summary>
</details>

Improve acked bitrate estimator

---

README.md
examples/chat.rs
src/change/sdp.rs
src/lib.rs
src/sdp/data.rs
src/sdp/parser.rs
tests/bidirectional.rs
tests/unidirectional.rs

The stream id is part of the msid mechanism for identifying streams that belong together and therefore should be synced.

New argument to add_media for setting stream_id

---

src/media/inner.rs
src/packet/pacer.rs
src/rtp/bandwidth.rs
src/session.rs

- Don't use queues for padding before first media
- Increase max consecutive padding packets
- Tweak pacing and padding rates

BWE tweaks

---

src/media/sender.rs
src/packet/buffer_rx.rs
src/rtp/header.rs
src/rtp/mod.rs
src/rtp/rtcp/mod.rs
src/rtp/rtcp/nack.rs
src/rtp/rtcp/twcc.rs
src/session.rs

This fixes a bug where the `MediaData::time` is not extended. The intention is that time will just keep going up.

Extend MediaTime

---

examples/chat.rs
src/lib.rs
src/media/inner.rs
src/media/mod.rs
src/packet/buffer_tx.rs
src/session.rs
tests/bidirectional.rs
tests/unidirectional.rs

Enqueing to the PacketizingBuffer requires a "queued_at" field which is "now". We don't want write() to drive time forward, which means we are temporarily storing the packets until next handle_timeout.
The expected behavior is:
1. MediaWriter::write()
2. to_packetize.push()
3. poll_output -> timeout straight away
4. handle_timeout(straight away)
5. to_packetize.pop()

Delay packetizer enqueue until handle_timeout

---

src/lib.rs
src/media/inner.rs
src/media/mod.rs
src/packet/buffer_tx.rs
src/packet/mod.rs
src/packet/pacer.rs
src/rtp/header.rs
src/rtp/mod.rs
src/session.rs

Previously packet burst of 5ms worth of the padding rate were sent
immediately and were not paced, in the process interrupting media
transmission. To alleviate this, this PR causes padding, like all other
packets, to be queued and paced. Padding is prioritized below all other
types of packets.

Pace padding as part of packet queues

---

src/media/inner.rs

Without this the after setting the direction back to send the pacer
would believe it could send padding, but since we clear all the media
state this is not true.

Clear queue state cache on direction change

---

src/dtls/ossl.rs
src/io/id.rs
src/io/stun.rs
src/lib.rs
src/rtp/id.rs
src/rtp/rtcp/mod.rs

This removes a bad `*const u8 as *mut u8` which breaks in nightly.
Further more we remove all use of `unsafe` and slap on the forbid directive.

Remove all use of unsafe and forbid it

---

src/media/inner.rs
src/packet/bwe/arrival_group.rs
src/packet/bwe/trendline_estimator.rs

We were dividing by 1000 instead of multiplying, however this was done
consistently which is why everything sill worked well. We will see if
this makes BWE as a whole more robust, especially under poor network
conditions.

Fix duration to ms conversion

---

src/packet/bwe/mod.rs
src/packet/bwe/rate_control.rs

We never stopped periodically adjusting BWE based on the current
trendline hypothesis, regardless of how old the hypothesis was. This
meant that if we had a hypothesis of underuse and stopped receiving TWCC
we would indefinitely increase the bandwidth estimate.
With this change we'll only consider a trendline hypothesis valid for a
while after the TWCC report that updated it.

Restrict periodic BWE adjustments

---

src/packet/buffer_tx.rs

This helps especially in the case of smaller buffer size

make it more likely to find spurious padding

---

src/change/sdp.rs
src/format.rs
src/sdp/mod.rs

Allow matching audio codecs with fuzzy logic i.e. allow disagreements about format parameters such as `useinbandfec` or `minptime`.

Fuzzy matching for audio codecs

---

src/rtp/rtcp/twcc.rs

One more iteration on egress loss reporting. I noticed that ingress loss causes a false positive in terms of egress loss. A TWCC packet being lost on ingress should be ignored when calculating egress loss, not have all the reported packets counted as lost.

Fix ingress loss being reported as egress loss

---

src/lib.rs
src/media/register.rs
src/packet/buffer_rx.rs
src/packet/vp8.rs
src/rtp/header.rs
src/rtp/mod.rs
src/session.rs

Chrome does not seem to answer nacks for frames on vp8 temporal layer 1 (since they are not vital). This means with some loss on the connection we introduce the highest delay possible (w.r.t. the configured amount of buffered video samples).
Here we aim at avoiding this

vp8: avoid waiting for intentionally unmet NACKs

---

src/media/inner.rs
src/session.rs

It's not a twcc_seq_no, so it shouldn't be named that.

Rename twcc_seq_no to seq_no

---

src/rtp/header.rs

now that we truncate away the padding, we can no longer pretend to read the payload of packets that are 100% padding.

avoid reading orig seqno from truncated padding

---

src/media/inner.rs

Happens while generating for feedback of all medias because `&mut feedback` is stored at session level.
I could have moved it in `session` but I think we don't need to clear the old feedback. It should be consumed way sooner and if it isn't I don't see why loose the information.

avoid one media clearing the feedback of another media

---

src/rtp/srtp.rs

Without this fix, an evil packet that claims it has padding and has an empty payload would cause a panic.

Don't panic on empty SRTP payload edge case

---

src/streams/send.rs

Modifying the pt when doing RTX meant subsequent resends of the same packet would fail
to be sent.

Fix incidental packet modification

---

src/media/mod.rs

Only do RTX fallback if we cannot find params based on main PT

Optimize Media::get_params for main PT

---

src/lib.rs
src/sdp/data.rs
src/sdp/mod.rs

This is useful to help identify our SDPs. Inspired by Firefox's o= line:
o=mozilla...THIS_IS_SDPARTA-83.0 7052848360639826063 0 IN IP4 0.0.0.0\r\n\
Like Firefox this data occupies the `<username>` component of the o=
line.
See https://www.rfc-editor.org/rfc/rfc4566#section-5.2

Add an identifier of str0m to the `o=` line in SDP

---

src/streams/mod.rs
src/streams/receive.rs
src/streams/rtx_cache.rs
src/streams/send.rs

The information is present in RtpPacket::header::payload_type.

Remove redundant RtpPacket::pt field

---

src/io/mod.rs
src/streams/send.rs

This fixes two problems.
1. We slightly increase the MTU warning to 1280.
2. We ensure the spurious padding doesn't exceed that value.

Fix MTU-clamping

---

src/stats.rs
src/streams/receive.rs

A given (mid, rid) pair can use multiple SSRCs. Not only is there an RTX
SSRC and a main SSRC, which was already handled prior to this commit,
but during the lifetime of an RTP Session new SSRCs (RTX and main) can be
created for the same (mid, rid) pair. In particular, Firefox does this
when a transceiver transitions from send to inactive, and back to send.
When media is resumed the original SSRCs are not used, instead new SSRCs
are created.

Merge stats for a given (mid, rid) pair

---

src/session.rs

When we received blank padding packets on the RTX stream those would end up getting
registered in the receive register for the main stream. This would in
turn cause us to NACK packets that never existed in the main stream.
The relevant code looked like this:
```rust
let receipt = if is_repair {
// Blank padding packets will have empty data.
if !data.is_empty() { // 1
// Rewrite the header, and removes the resent seq_no from the body.
stream.un_rtx(&mut header, &mut data, pt);
}
// Now update the "main" register with the repaired packet info.
// This gives us the extended sequence number of the main stream.
//
// We need to do this also for blank padding to schedule the "paused event".
let receipt = stream.update(now, &header, clock_rate, false); // 2
// Drop blank padding
if …
```

Fix RTX seq num ending up in main receive register

---

src/packet/bwe/mod.rs
src/rtp/rtcp/mod.rs
src/session.rs

The calculation is in hot loops and only updates with TWCC.
Also avoid allocation of RTCP VecDeque.

bwe: precalculate mean_max_rtt

---

src/change/sdp.rs
src/media/mod.rs
tests/common.rs
tests/sdp-negotiation.rs

If a remote peer tries to transition an inactive m-line, that it didn't
create, to recvonly we ignore this and keep it inactive in our answer.
Only the creator of the m-line is allowed to make this transition.

Ignore transition inactive->recvonly by remote peer

---

src/dtls/mod.rs
src/dtls/ossl.rs
src/lib.rs
src/rtp/mod.rs
src/rtp/srtp.rs
src/session.rs

This PR adds support for `SRTP_AEAD_AES_128_GCM` profile as an alternative to `SRTP_AES128_CM_SHA1_80`.
`SRTP_AEAD_AES_128_GCM` is more performant than `SRTP_AES128_CM_SHA1_80`, initial testing shows an improvement of about 50%, however I have not done proper benchmarking.
This PR is here:
```
1. Make it work <––
2. Make it beautiful
3. Make it fast
```
The code that implements the various profiles in `src/rtp/srtp.rs` could stand to be improved in making this beautiful.
There are a few outstanding `TODO`s that would be good to discuss, for now I've disabled `SRTP_AEAD_AES_128_GCM` in the DTLS handshake so we can merge this PR.

Add support for SRTP_AEAD_AES_128_GCM

---

src/streams/receive.rs

https://www.rfc-editor.org/rfc/rfc5104#section-4.3.1
Seq nr. (8 bits): Command sequence number.  The sequence number
space is unique for each pairing of the SSRC of command
source and the SSRC of the command target.  The sequence
number **SHALL be increased by 1 modulo 256** for each new
command.  A repetition SHALL NOT increase the sequence
number.  The initial value is arbitrary.
This was not implemented correctly and would panic(with overflow checks
enabled).

Fix overflow in FIR seq no

---

src/io/mod.rs
src/rtp/header.rs
src/streams/rtx_cache.rs
src/streams/send.rs

```
thread 'tokio-runtime-worker' panicked at 'range end index 48 out of range for slice of length 46', /home/ubuntu/work/lookback/str0m/src/streams/rtx_cache.rs:53:22
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
./bin/dev.sh: line 12:  2131 Aborted                 (core dumped) cargo run -- --watch --enable-simulcast
```

fix quantized_size index of out bounds

---

src/session.rs

When using ssrc we registered rtx as it own mid instead of looking up the main ssrc and register rtx on the main stream.
This lead to problems when looking up stream by mid we could get the rtx ssrc instead of the main one and hence we did not request keyframes on the correct ssrc.

bug: Use ssrc_main when calling expect_stream_rx

---

src/change/direct.rs
src/dtls/mod.rs
src/ice/agent.rs
src/lib.rs

This commit introduces few minor changes to `str0m`:
* allow user to set local ICE credentials
* allow user to disable certificate fingerprint verification
* allow user to fetch remote's certificate fingerprint
These changes allow implementing WebRTC Direct [1] using `str0m`
[1] https://github.com/libp2p/specs/blob/master/webrtc/webrtc-direct.md
---
Related to #166 
cc @thomaseizinger @xnorpx

Implement missing features needeed for WebRTC Direct

---

src/change/direct.rs
src/lib.rs
src/rtp/mod.rs
src/rtp/mtime.rs
src/rtp/rtcp/mod.rs
src/rtp/rtcp/sr.rs
src/rtp/rtcp/xr.rs
src/streams/receive.rs
src/streams/send.rs
src/util/mod.rs
src/util/time_tricks.rs

- Expand PAST constant to also have SystemTime
- Consolidate time tricks into util/time_tricks
- Refactor to_unix_duration to use beginning_of_time
- Rename PAST constant to BEGINNING_OF_TIME
- Instant::from_ntp_u64 and as_ntp_u64

Time fixes

---

examples/chat.rs
src/lib.rs
src/media/writer.rs
tests/bidirectional.rs
tests/unidirectional-r-create-media.rs
tests/unidirectional.rs
tests/user-rtp-header-extension.rs

In #339 was decided to change `Writer::write` `data` parameter to be `Into<Vec<u8>>` instead of `&[u8]`, because it will allow the caller to pass either a `Vec<u8>` (without cloning) or something else. 
Also it will be more obvious that this method needs owned `data`.

Use `Into<Vec<u8>>` instead of `&[u8]` in `Writer::write`

---

src/streams/register.rs

- add test for out of order packets on rollover
- rx buffer: skip seqs before nack_check_from

alt fix for nack register rollover

---

src/change/sdp.rs
src/rtp/ext.rs
src/sdp/data.rs
src/session.rs
tests/sdp-negotiation.rs

Firefox has bugs with dynamically establishing the mappings of SSRCs for
simulcast using the rid and repaired-rid RTP header, however it does
send the `ssrc-group` correctly in SDPs. To workaround these bugs we
need to give preference to the mapping signalled via ssrc-group, if
enabled.

Respect `ssrc-group` simulcast signalling

---

src/session.rs

We were rounding up which meant that we ended up with a max size of 1132
and when the SRTCP overhead of 20 bytes was added to this we exceeded
the 1150 MUT limit. This happened because we were rounding up. Now we
round down instead, so we'll end up with a size of 1128 for a max
encrypted size of 1148.

Fix MUT rounding for RTCP packets

---

src/session.rs
src/streams/mod.rs
src/streams/receive.rs
src/streams/register.rs
src/streams/register_nack.rs

- separate nack and RR generation
- remove misorder delay
- remove probation period
- simplify handing nack to avoiding unnecessary operations

rx register rewrite

---

src/media/mod.rs
src/packet/payload.rs

Previously, it was assumed that the denominator of RTP time passed to media writers was the clock rate of the media but this is not necessarily the case. As the RTP packet is prepared for writing, this adjustment (if any) should be done. To accomplish this, `Payloader` now takes a whole `CodecSpec` and produces the packetizer and a copy of the clock_rate parameter from this. This will allow the `MediaTime` rational number abstraction to function in the API as expected and make working with, e.g., pre-recorded source streams easier.

Payloader: rebase rtp_time to the codec's clockrate

---

src/channel.rs

This patch improves the `Debug` output for `ChannelData` containing text. If the text parses as UTF-8 and is also ASCII, it will be included in the output. Otherwise, if the text does not parse as UTF-8, an error is shown or if it's non-ASCII, the length is presented as before.

channel: improve Debug output for ChannelData text

---

src/packet/buffer_rx.rs
src/packet/buffer_rx/vp8_contiguity.rs
src/packet/vp8.rs
src/streams/register_nack.rs
tests/contiguous.rs

This PR improves how we wait for retransmissions and detect discontinuities in our sample-based api (MediaData). This is relevant for VP8 when temporal layers are enabled (simulcast) in case of network loss.
 Fixes issue with minor corruption on Chrome improves major corruption on Safari (it’s less frequent and when it happens the discontinuity is reported).

VP8 L1T3 compat

---

src/change/sdp.rs
src/media/mod.rs
src/rtp/ext.rs
src/sdp/data.rs
src/session.rs
tests/sdp-negotiation.rs

In #346 we attempted to workaround some bugs in Firefox to do with establishing the SSRC mappings for simulcast media. 
We took the approach of always relying on the information communicated via SDP i.e. `a=ssrc-group`, however it turns out 
this information is not reliable and what we should have relied on is the information communicated via the `rid` and `repaired-rid`
RTP headers exclusively.
This PR also fixes an issue where hangover state in `DepacketizingBuffer` would cause it to not emit samples when the SSRC for a given 
(Rid, Mid) pair, or just Mid in the case of non-simulcast, changes.

Rework Firefox SSRC workaround

---

src/change/sdp.rs

Related to #364
Sometimes, when using `str0m`, users may need to run a a second negotiation while first one is still in progress. 
To make this possible, I suggest adding an API that lets us combine a `SdpPendingOffer` with new changes from `SdpApi`. This combination will produce a new `SdpOffer` and a fresh `SdpPendingOffer`. These new offer will include changes from the previous `SdpPendingOffer` as well as new changes from `SdpApi`. The original `SdpPendingOffer` will still be available for users, allowing them to cancel any `SdpAnswer` related to the previous `SdpOffers`. This can be done using the `ChangeId` stored in the original `SdpPendingOffer`.
It's important to note that these older `SdpPendingOffers` will be empty and won't make any changes. Only the latest `SdpPendingOffer` …

SdpPendingOffer merging

---

src/lib.rs

This fixes a bad bug where a lot of packets were thrown away
for big SCTP payload.
Close #382

Send all SCTP packets

---

src/streams/send.rs
src/util/value_history.rs

Based on this capture ValueHistory contributes to the heaviness of str0m::session::Session::poll_packet
Tested locally these 2 alternatives
```
+        for _ in 0..1_000_000 {
+            h.push(now, 22);
+
+            // 1
+            h.sum_since(now - Duration::from_secs(1));
+            // 2
+            h.sum();
+
+            now += inc;
+        }
```
This goes from 2s to 0.05s

send stats performances

---

src/change/sdp.rs
src/rtp/ext.rs
src/rtp/header.rs
tests/sdp-negotiation.rs
tests/user-rtp-header-extension.rs

While in there, also refactor ExtensionMap.iter() to allow for iterating over all extensions.

Add support for 2-byte header extensions

---

src/io/mod.rs

when debugging ice connectivity check when running str0m as a client I noticed proto was missing from debug of transmit.

Add proto to Transmit debug

---

src/ice/candidate.rs
src/sdp/data.rs
src/sdp/mod.rs
src/sdp/parser.rs

* When used with serde_json, it will generate:
```json
{
"candidate": "candidate:12044049749558888150 1 udp 2130706175 1.2.3.4 9876 typ host ufrag ufrag",
"sdpMid": null,
"sdpMLineIndex": 0,
"usernameFragment": "ufrag"
}
```
* It will ignore `sdpMid` and `sdpMLineIndex` and set them to null and 0 respectively, because 1) `Candidate` does not store these values, and 2) ICE candidates require them to [not be null](https://developer.mozilla.org/en-US/docs/Web/API/RTCIceCandidate/sdpMLineIndex#value)).
* Also add `pub fn from_sdp_string(s: &str)` and `pub fn to_sdp_string(&self) -> String`
* Display/from_str now doesn't return an sdp m-line.

Serialize/Deserialize Candidate

---

src/packet/pacer.rs

This prevents a hot loop when you enable RTX for audio and BWE/pacing at the same time without having to know to call .set_unpaced(false) for the audio.

Send unpaced media as padding.

---

src/sdp/data.rs
src/sdp/parser.rs

This PR adds ability to receive offer with simulcast including some inactive `rid`s ([marked with "~" prefix](https://datatracker.ietf.org/doc/html/rfc8853#name-simulcast-attribute)) and to generate correct answer.

Fix SDP for inactive `rid`s

---

src/change/sdp.rs
src/lib.rs
src/media/writer.rs

As in #345, a regression was introduced by a recent refactoring where only payload params for a given mid should be produced but all payload params were being used instead.

Writer payload params bugfix

---

src/bwe.rs
src/format.rs
src/lib.rs
src/rtp/rtcp/mod.rs
src/rtp/rtcp/remb.rs
src/rtp/rtcp/rtcpfb.rs
src/sdp/data.rs
src/session.rs
src/streams/mod.rs
src/streams/receive.rs
src/streams/send.rs
tests/remb.rs

I am currently developing a decentralized media server. In some cases, we need a way to limit the sending bitrate from the sender. For example, in a conference room, we need to adapt the sending bitrate to accommodate viewers with slow internet connections.
The current implementation of str0m only supports TWCC, meaning only the sender can control the sending bitrate. To address this, I have added the REMB mechanism, which works on the receiver side, similar to FIR or PLI.
For more details on usage, please refer to my media server implementation:
https://github.com/8xFF/decentralized-media-server/blob/0102e4cda023efa5671f4ac440659a25ae5d0c66/transports/webrtc/src/transport.rs#L178-L185

Implement REMB (Receiver Estimated Maximum Bitrate)

---

src/sdp/parser.rs

SDP from stun enabled client has some Candidate which failed to parse like:
```
a=candidate:3684617590 1 udp 2122260223 10.217.229.219 50028 typ host generation 0 network-id 1 network-cost 900
a=candidate:387183333 1 udp 1686052607 113.185.55.72 31267 typ srflx raddr 10.217.229.219 rport 50028 generation 0 network-id 1 network-cost 900
a=candidate:2501718406 1 tcp 1518280447 10.217.229.219 9 typ host tcptype active generation 0 network-id 1 network-cost 900
a=candidate:387183333 1 udp 1686052607 113.185.55.72 41775 typ srflx raddr 10.217.229.219 rport 50028 generation 0 network-id 1 network-cost 900
```
Which caused failed to connect to libwebrtc client with STUN-Nat-Traversal

fix: wrong parse ice-candidate with generation, network-id or network-cost

---

src/format.rs
src/media/mod.rs
src/packet/buffer_rx.rs
src/packet/payload.rs
src/rtp/ext.rs
src/rtp/mod.rs
src/rtp/mtime.rs
src/rtp/rtcp/mod.rs
src/rtp/rtcp/sr.rs
src/sdp/data.rs
src/sdp/parser.rs
src/streams/mod.rs
src/streams/receive.rs
src/streams/rtx_cache.rs
src/streams/send.rs
src/streams/send_queue.rs
tests/sdp-negotiation.rs

`as u64` of `i64` is dangerous. `Duration` is non-negative but `MediaTime` is not necessarily. This fixes what is effectively an integer underflow.

MediaTime: fix negative value into Duration bug

---

src/ice/agent.rs

Previously, `accept_message` would validate that incoming STUN requests match the credentials we have locally. This allows a server to de-multiplex, which agent should handle an particular STUN request.
In a peer-to-peer setting, both parties will make STUN requests and thus, we also need to de-multiplexing incoming STUN replies. Luckily this is quite easy because the candidate pairs that we have formed locally keep track of the transaction IDs that we've used so far. If an inbound message is a STUN reply but we don't recognise the transaction ID, we now return `false` from `accepts_message`.

De-multiplex STUN replies based on transaction ID

---

CHANGELOG.md
src/io/stun.rs

The only usage site of `StunError::Other` is an `io::Error` which we already have a variant for.

Remove `StunError::Other`

---

CHANGELOG.md
Cargo.toml
src/change/direct.rs
src/change/mod.rs
src/change/sdp.rs
src/ice/agent.rs
src/ice/mod.rs
src/io/mod.rs
src/io/stun.rs
src/lib.rs
src/sdp/data.rs
src/sdp/parser.rs

In order to allow low level access to `ice` in a similar way as `rtp`, we introduce a public `ice` module that rexports `IceAgent` and `IceAgentEvent`. In addition, we also export `StunMessage` publicly from the `ice` module. To keep the public API small, all functions apart from `StunMessage::parse` are marked as `pub(crate)`. For standalone usage of `IceAgent`, we only need to be able to parse `StunMessage`s but not expose any other details.

Allow low-level access to `IceAgent`, `IceAgentEvent` & `StunMessage` via `ice` module

---

src/dtls/mod.rs
src/ice/agent.rs
src/ice/mod.rs
src/io/mod.rs
src/lib.rs
src/session.rs

Currently, `net::Receive` is used to parse and de-multiplex incoming messages between STUN, DTLS, RTP and RTCP. `Rtc` however does not use the parsed message and instead passes on the entire `net::Receive` struct to the sub-components. This requires each low-level component like `Dtls`, `Session` and `IceAgent` to revalidate that they are in fact only being passed the data that they can handle.
To fix this, we change the signatures of the various `handle_receive` functions to only take in the parsed message. For DTLS, RTP and RTCP, this is only a byte-buffer which isn't the most type-safe way to go about it. Those APIs are crate-private though so for now, this isn't be a big issue.

Decouple low-level components from `net::Receice`

---

src/io/mod.rs
src/io/stun.rs
src/lib.rs

Currently, attributes are parsed into a `Vec` which results in an allocation for each STUN message that is parsed. We only support a limited set of attributes in `str0m` so this can also be expressed using `Option`s which allows us to parse STUN messages allocation free.
As a result, `StunMessage` now implements `Copy`!

Don't allocate while parsing `StunMessage`

---

src/io/stun.rs

I had to remove the two links in order to make rustfmt actually align those comments. For `software`, I added the attribute ID as it is done for some of the others.

Align comments in on fields in `Attributes`

---

.gitignore
Cargo.lock
Cargo.toml
_str0m_test/Cargo.lock
_str0m_test/Cargo.toml
_str0m_test/src/lib.rs
fuzz/Cargo.toml
fuzz/fuzz_targets/rtx_buffer.rs
run-fuzz.sh
src/_internal_test_exports/fuzz.rs
src/_internal_test_exports/mod.rs
src/format.rs
src/ice/candidate.rs
src/lib.rs
src/rtp/header.rs
src/sdp/data.rs
src/sdp/parser.rs
tests/common.rs
tests/ice-restart.rs
tests/sdp-negotiation.rs

The feature `_internal_test_exports` enables code that is used for integration tests and fuzzing. This PR also makes `pub(crate)` of a bunch of `fn`s that were `#[doc(hidden)]`. That might break someone's code downstream, but we want to at least have code documentation on which functions are de-facto public API (or consider making them proper public API).

Feature _internal_test_exports for tests and fuzz

---

src/io/mod.rs
src/lib.rs
src/media/mod.rs
src/sdp/data.rs
src/session.rs

- Properply hide contents of DatagramRecv
- Code doc for some #[doc(hidden)]
- Refactor away Event::Error hack

Rework some #[doc(hidden)]

---

src/rtp/rtcp/twcc.rs

TwccRecvRegister queue is sorted list so we don't have to finding max seq with bellow code.
https://github.com/algesten/str0m/blob/b73fe14cd06a7b630ee7cf5ac0129e852fe12bcc/src/rtp/rtcp/twcc.rs#L264-L270
After change bellow simple publisher-viewer single audio track benchmark speedup from 5.2 Kelm/s to 356.15 Kelm/s
```rust
let (mut l, mut r) = connect_l_r();
let mid = "aud".into();
// In this example we are not using RID to identify the stream, we are simply
// using SSRC 1 as knowledge shared between sending and receiving side.
let ssrc: Ssrc = 1.into();
l.direct_api().declare_media(mid, MediaKind::Audio);
l.direct_api().declare_stream_tx(ssrc, None, mid, None);
r.direct_api().declare_media(mid, MediaKind::Audio);
r.direct_api().expect_stream_rx(ssrc, None, mid, None);
let max = …
```

fix: TwccRecvRegister max_seq slow

---

src/format.rs

Current Codec.is_video function is missing H265 type. This PR just add H265 Codec type to is_video function.

fix: is_video func missing h265

---

src/packet/bwe/trendline_estimator.rs

Then intent is to set the initial hypothesis to `BandwithUsage::Normal`, but due to the lack of `return` this didn't happen.

Fix missing return in TrendlineEstimator::detect

---

src/media/mod.rs
src/streams/mod.rs
src/streams/rtx_cache.rs
src/streams/send.rs

[One of our users reports](https://str0m.zulipchat.com/#narrow/stream/377845-general/topic/Getting.20panic.20.22pt_rtx.20resend.2Fblank.22/near/412721167) that we got an `expect()` that trips. Any expect/unwrap that trips means we have a bug.
`/src/streams/send.rs:382:45: pt_rtx resend/blank`
The code in question:
```rs
NextPacketKind::Resend(_) | NextPacketKind::Blank(_) => {
let pt_rtx = param.resend().expect("pt_rtx resend/blank");
```
Whenever we have a `Resend` or `Blank` packet, we assume the RTX PT is known. This is sometimes (apparently) not true. Rather than dwelling on exact root cause, I've rewritten the code in question to have a more robust way of detecting which RTX PT to use. It should also be impossible to produce a `Resend` or `Blank` if the PT isn't known.

Robust(er) RTX PT allocation for StreamTx

---

src/io/stun.rs

When the `debug` log level is activated, str0m logs each STUN request that it sends. This is useful but in its current configuration very noise, see:
```
| 2024-01-25T01:08:01.612757Z DEBUG str0m::ice_::agent: Send STUN request: 172.18.0.3:50261 -> 172.20.0.3:52550 StunMessage { method: Binding, class: Request, attrs: Attributes { username: Some("gpzm:qUls"), message_integrity: None, error_code: None, realm: None, nonce: None, xor_mapped_address: None, software: None, fingerprint: None, priority: Some(1862270719), use_candidate: false, ice_controlled: None, ice_controlling: Some(7816118197453770412), network_cost: None }, integrity_len: 0 }
```
This PR only logs the fields that are actually set which will transform the above into:
```
| 2024-01-25T01:08:01.612757Z DEBUG …
```

feat: minimal `fmt::Debug` impl for STUN `Attributes`

---

src/ice/candidate.rs

Without further adjustments, this will set `Transmit.source` to the provided base here. Opening this here because we are (temporarily) depending on it.
Resolves: #453.

feat: explicitly set `base` of server-reflexive addresses

---

src/ice/agent.rs

Fixes https://github.com/algesten/str0m/issues/460
As a summary of that discussion, if you have two `Rtc` instances, one negotiated and the other not, and you pass incoming STUN traffic intended for the negotiated instance to the `Rtc::accepts()` of the non-negotiated instance, it will panic in `stun_credentials` because without an offer, no remote ICE credentials will have been sent. This PR simply checks for this case first.

Fix panic in Rtc::accepts() with STUN traffic

---

src/ice/agent.rs

Currently, the `info` log is a bit misleading because it suggests that we are discarding a candidate over and over again.

feat: only log about discarded candidate on INFO if we change state

---

src/ice/agent.rs

chore: only add on INFO log about new candidates if we actually change state

---

src/io/stun.rs

This API is most likely called with a buffer read from the network. We need to guard against being given a buffer that is too short.

fix: don't panic on parsing `StunMessage` from 0-length buffer

---

src/ice/agent.rs

When calling `IceAgent::ice_restart`, we always see the following logs:
```
2024-03-13T23:54:12.115048Z  INFO str0m::ice_::agent: ICE restart
2024-03-13T23:54:12.115057Z  INFO str0m::ice_::agent: State change (ice restart): Completed -> Checking
```
This PR removes the first one because it is superfluous.

chore: remove superfluous "ICE restart" log

---

src/ice/agent.rs

While the bug mentioned in https://github.com/algesten/str0m/pull/461 was real as of version `0.4.1`, it had since been fixed by https://github.com/algesten/str0m/pull/418, rendering my fix redundant.
My fix also caused a regression - STUN binding requests received before remote credentials were set were being dropped by `IceAgent.accept_message()`, instead of being let through and subsequently buffered via `IceAgent.stun_server_queue`.
Rather than just revert the PR, this also adds a test to catch further regressions of this buffering.

Revert #461 and add a regression test for what it broke.

---

src/format.rs
src/sdp/data.rs

This adds support for an Opus format param `usedtx`, which signals a receiver's preference for DTX. DTX stands for [Discontinuous Transmission](https://datatracker.ietf.org/doc/html/rfc7587#autoid-7), and it's a feature in Opus that lowers the packet rate, not just the bitrate, during periods of silence. For instance, in my WebRTC environment, Chrome and Firefox will reduce the packet rate from 50 packets per second to 4 during silence. This makes it ideal for SFU-type applications, where any particular person spends most of the time not talking, and so we can save the CPU time spent processing such packets.
As mentioned in the above link, it does have slight effects on the resulting audio, and browsers don't currently negotiate it without SDP munging, so here I've set it off by default. …

Opus DTX support

---

src/ice/agent.rs
src/io/mod.rs
src/io/stun.rs

An unrelated bug I had in my application was causing STUN to fail, and a `Class::Failure` message to come back. Because like in the chat example, I'm still using a single multiplexed UDP socket, this message first went to the `Rtc::accepts()` of a separate client that had not negotiated, which caused it to panic with "Remote ICE Credentials".
This is the same underlying panic as in https://github.com/algesten/str0m/pull/461, but this time the logic was allowed to fall through to the `stun_credentials()` call because we were only doing the preceding candidate-pair test for `Class::Success` responses, not `Class::Failure`.
I wanted to add a test for this, but with the current field visibility on `StunMessage`, I couldn't create a failure message in a test. I wasn't sure if adding a helper …

Fix panic on STUN binding failure while multiplexing

---

src/ice/agent.rs
src/lib.rs

fix: don't panic on STUN requests for unknown interfaces

---

src/format.rs

Currently, VP9 is only matched by exact match, leading to potential issues with sessions in Chrome and Firefox browsers. The problem arises from Firefox not setting the `profile_id`, causing str0m to interpret Firefox's `PayloadParams` as incompatible with Chrome. According to [the VP9 specification][0], when `profile_id` is unset, it should default to `0`. This pull request addresses this issue by implementing the functionality to default `profile_id` to `0` in the fuzzy match of VP9.
> If no profile-id is present, Profile 0 MUST be inferred.  (The profile-id parameter was added relatively late in the development of this specification, so some existing implementations may not send it.)
[_draft-ietf-payload-vp9-16#section-6_][0]
[0]: …

Implement VP9 `PayloadParams` fuzzy matching

---

src/change/direct.rs
src/media/mod.rs
src/media/writer.rs
src/streams/mod.rs

In commit "Lazily enable nack timeouts" ([f72b690][1]) was introduced optimization of NACK timeouts enabling, this commit added `Streams::any_nack_enabled` resetting in `Streams::stream_rx_by_mid_rid()`, but `Streams` has exact the same method called `Streams::rx_by_mid_rid` (which is used under the hood in `Direct::stream_rx_by_mid`) which wasn't updated. So if you're getting `StreamRx` from Direct API and call `suppress_nack(false)` on it, then `any_nack_enabled` is not updated, resulting in NACKs not being transmitted.
This PR removes this duplication of methods `rx_by_mid_rid` and `tx_by_mid_rid` in favor of `stream_tx_by_mid_rid` and `stream_rx_by_mid_rid`.
[1]: https://github.com/algesten/str0m/commit/f72b690dc7961dc40d1c30f1bbbc692d83b13125

Fix lazy NACK timeouts enabling

---

src/ice/agent.rs

We ran into a bug where a candidate was incorrectly invalidated based on IP only without considering the kind of candidate. The bug was in our software because we didn't invalidate a host candidate and our tests didn't catch it because there, we invalidated it "accidentially" by wanting to invalidate the corresponding srflx candidate. The (unit)-tests don't have a NAT so there host == srflx. But in the real world, we had a NAT but the two nodes were on the same subnet, thus they ended up making a host-host connection and failed to migrate that to another candidate because it was never invalidated.

fix: only invalidate candidates of the same kind

---

src/io/stun.rs

In [litep2p](https://github.com/paritytech/litep2p/) we are using the low-level ice module to handle connections.
We'd need the to split the username attribute from a [StunMessage](https://github.com/algesten/str0m/blob/428e3dbe054cd4a11019394b5553b3049879be68/src/io/stun.rs#L71) object to instantiate an rtc client.
- https://github.com/paritytech/litep2p/blob/e03a6023882db111beeb24d8c0ceaac0721d3f0f/src/transport/webrtc/mod.rs#L347-L386
This is the missing functionality that currently blocks our migration from 0.4.1 to 0.5 (which includes a needed fix for us: https://github.com/algesten/str0m/commit/7ed5143381cf095f7074689cc254b8c9e50d25c5).
Would love to hear your thoughts on this, and if you think another approach would be more appropriate, thanks! 🙏

io/stun: Expose `split_username` publicly

---

src/ice/agent.rs
src/ice/candidate.rs
src/ice/mod.rs

This fixes re-adding of previously invalidated ice candidates.
Close #507

Re-add invalidated remote/local candidates

---

src/change/sdp.rs
tests/user-rtp-header-extension.rs

If I enable VLA rtp extension, then the str0m will crash with error: `internal error: entered unreachable code: Incorrect ExtensionSerializer::is_video` (full crash log is attached in bellow).
The reason is when str0m parse SDP string, it will parse all non-str0m-standared extensions as a SdpUnknowUri. Then when creating an answer, it uses SdpUnknowUri instead of config from RtcConfig as described in https://github.com/algesten/str0m/blob/3902a6d27f1b0b5dbf91d91394853d6711bb009a/src/change/sdp.rs#L1034-144
```rust
let mut remote_extmap = ExtensionMap::empty();
for (id, ext) in m.extmaps().into_iter() {
// The remapping of extensions should already have happened, which
// means the ID are matching in the session to the remote.
if exts.lookup(id) != Some(ext) {
// Don't set any extensions …
```

fix: crash when set custom rtp extension

---

src/ice/agent.rs
src/lib.rs
src/session.rs
src/streams/receive.rs
src/streams/send.rs

To reduce the chattiness on debug move some packet level logging to trace.

Tune some logging levels

---

src/bwe.rs
src/packet/bwe/acked_bitrate_estimator.rs
src/session.rs

This PR have some changes:
- Fix some missing when porting [bitrate_estimator.cc](https://webrtc.googlesource.com/src/+/9f3ccf291e/modules/congestion_controller/goog_cc/bitrate_estimator.cc) from libwebrtc.
- Added bwe reset API
For more clearly, I will explain what issues lead to this PR. 
When an audio stream starts before a video stream, the Bitrate Estimator (BWE) calculates the initial bitrate based on the audio packets. This results in a very low estimated bitrate, typically around 40kbps. When the video stream starts, the BWE struggles to adapt to the increased bandwidth requirements, leading to a slow increase in bitrate. This can cause poor video quality.
```rust
let sample_estimate_bps = sample_estimate.as_f64();
let estimate_bps = estimate.as_f64();
// Define the sample …
```

BWE increases slowly when audio packets are sent before video packets

---

docs/ice.md
src/change/sdp.rs
src/ice/agent.rs

Resolves https://github.com/algesten/str0m/issues/513. However, it does not make Lite-to-Lite connections fully functional - details below.
[RFC 5245](https://www.rfc-editor.org/rfc/rfc5245#section-5.2) says:
- In a Full-to-Full connection, the initial offerer takes the controlling role in ICE.
- In a Full-to-Lite connection, the Full peer takes the controlling role, regardless of which side offered.
- In a Lite-to-Lite connection, again the initial offerer takes the controlling role.
However, behavior prior to this PR would always consider the initial offerer to be controlling, irrespective of ICE Lite. This discrepancy caused role confusion and thus connection issues when the initial offerer was ICE Lite, regardless of that offerer being str0m itself or another client.
The RFC's logic …

SDP negotiation now considers ICE Lite when determining ICE role

---

src/rtp/rtcp/twcc.rs

Resolves https://github.com/algesten/str0m/issues/523.
While working on this, I found another issue when you have deltas that are big enough to overflow when cast down to an `i32`. This wasn't panicking, but would nevertheless cause strange results. The second commit contains a fix for this as well.

Fix big TWCC time deltas

---

src/session.rs
src/streams/receive.rs

Currently we update the TWCC and Nack registers even if we don't manage to decrypt the SRTP and/or remove the padding. This means a corrupted UDP packet might still count as successful wrt to resends and bwe.

Update nack/twcc register after SRTP decrypt

---

src/io/mod.rs

`MultiplexKind` (and, by extension, callers such as `DatagramRecv`) didn't check for an empty buffer before attempting to read the first byte, causing a panic.

Fix panic in `DatagramRecv::try_from` with empty buffer

---

src/_internal_test_exports/fuzz.rs
src/session.rs
src/streams/mod.rs
src/streams/receive.rs
src/streams/register.rs
src/streams/register_nack.rs

We got code for dynamically discovering SSRC changes. This is detected when a mid/rid or mid/pt header combo starts on one SSRC and then changes to another. 
As a special case, it could happen that the sender reuses an SSRC it used previously. 
A -> B -> A
The SRTP IV is derived from the extended sequence number. If one IV is reused even once, the encryption is broken. Hence the sender is not allowed to reuse sequence numbers. 
That means the above scenario, where we reuse a previously used SSRC, we must remember the old sequence number to be able to restart from the correct ROC.

Remember max rx SeqNo per SSRC

---

src/ice/agent.rs
src/ice/mod.rs
src/ice/pair.rs
src/io/mod.rs
src/io/stun.rs

This makes the 3 components that make up the ICE timeout configurable. I tried to add some documentation to the setters to the best of my understanding of how this works internally.
Resolves: #490.

feat(ice): make timeout values configurable

---

src/media/writer.rs

This adds a function with the signature `pub fn playout_delay(mut self, min: MediaTime, max: MediaTime) -> Self` to the `Writer` that allows the minimum and maximum playout delay values to be set. Feel free to change the doc comment (I wasn't sure exactly how much information to put there).

Add `playout_delay` builder function to `Writer`

---

src/ice/agent.rs
src/ice/pair.rs

When we encounter a new candidate pair that replaces an existing one, we currently set the `NominationState` of the new pair to `Nominated` or `Success`, depending on whether the replaced one was `Nominated`.
This can result in an erroneous nomination of a candidate pair that previously had its `NominationState` set to `None`. `was_nominated` is `false` in that case which ends up setting the new `NominationState` to `Nominated`.
The correct behaviour is to strictly mirror the nomination state only if it is either `Nominated` or `Success`.

fix: mirror nomination state when replacing candidate pair

---

src/change/sdp.rs
src/sctp/mod.rs

Make it possible to configure reliability and ordering when creating data channels through the SdpApi by having `SdpApi::add_channel` take a ChannelConfig.
It might make sense to add convenience methods for common configs e.g. `ChannelConfig::reliable(label)` or `SdpApi::add_reliable_channel(label)`.
With this change it's not clear how to create out-of-band negotiated channels, since on the side that will generate the initial answer applying added channels will create an offer. My guess is adding them after accepting the initial offer would work, but this should be documented.

ChannelConfig for data channels in SdpApi

---

Cargo.lock
Cargo.toml
src/crypto/ossl/cert.rs

Change the `unix_time` function to return `libc::time_t` instead of a hard-coded `i64`.
This PR attempts to fix the following error when compiling to the armv7 platform.
```
cargo build --target armv7-unknown-linux-gnueabihf
Compiling str0m v0.5.1 (/home/magine/str0m)
error[E0308]: mismatched types
--> src/crypto/ossl/cert.rs:50:42
|
50  |         let before = Asn1Time::from_unix(unix_time() - 3600)?;
|                      ------------------- ^^^^^^^^^^^^^^^^^^ expected `i32`, found `i64`
|                      |
|                      arguments to this function are incorrect
|
note: associated function defined here
--> /home/magine/.cargo/registry/src/index.crates.io-6f17d22bba15001f/openssl-0.10.59/src/asn1.rs:330:12
|
330 |     pub fn from_unix(time: time_t) -> Result<Asn1Time, …
```

Change the `unix_time` function to return `libc::time_t` instead of a hard-coded `i64`

---

src/change/sdp.rs
src/sdp/data.rs

So I`ve been experimenting with AV1 SVC, and it seems that Chrome won't send  [Dependency Descriptor RTP Header Extension](https://aomediacodec.github.io/av1-rtp-spec/#dependency-descriptor-rtp-header-extension) if [a=extmap-allow-mixed](https://www.rfc-editor.org/rfc/rfc8285.html#section-6) is not signaled by the remote, so here it is.

Add `extmap-allow-mixed` SDP attribute

---

src/media/mod.rs
src/sdp/data.rs

Get the stream_id and track_id from the incoming MediaLine and expose them to users on the resulting Media so they can tell incoming Media apart. Should the incoming Media not have a Msid attribute this falls back to the previous behavior of generating random ids

Support getting stream_id and track_id of Media

---

src/ice/candidate.rs

fix: ensure lexical ordering of SDP-formatted candidates follows priority

---

src/ice/agent.rs
src/ice/mod.rs

In case the active candidate pair gets invalidated, str0m currently instantly emits a `Disconnected` event. For example, if a candidate pair with a peer-reflexive candidate gets nominated and later replaced. This results in a disconnected event despite us not actually being disconnected (a peer-reflexive candidate that gets replaced is after all the exact same socket).
To avoid this false-positive disconnection, we transition back to `Checking` in case we are still evaluating other candidates.

fix(ice): do not disconnect whilst we still check new candidates

---

src/media/event.rs
src/media/mod.rs
src/packet/buffer_rx.rs
tests/common.rs
tests/rtp_to_frame.rs

When implementing an Audio Jitter buffer, information about new talkspurts can be used to do adjustments to the buffer.
Marker bit is available in the rtp api, but for the sample(frame) api we need it exposed.

Make start of talkspurt information available for sample api

---

src/ice/candidate.rs

rustc 1.82-beta in [this commit](https://github.com/rust-lang/rust/commit/0ba9db87e61adcfd9a978188f61c20d9b423a099) changes something about how hashes are calculated (likely [this PR](https://github.com/rust-lang/rust/pull/128946)). Since our tests have pinned hash values, we get a breakage.
Since we uphold MSRV 1.65, we can't pin the hash in the test since we will get broken CI tests when we ensure the MSRV compiles.

Fix tests for rustc 1.82-beta

---

src/rtp/mtime.rs

I'm not sure why these were removed in https://github.com/algesten/str0m/pull/521. 
This adds them back, matching the behaviour of `std::time::Duration`

Add Sub methods to `MediaTime`

---

CHANGELOG.md
src/streams/send.rs
src/util/value_history.rs

So i've noticed remote receivers sending PLIs too often even after minor packet loss. Debugging NACKs and RTXs showed that everything actually works fine for some time and at some point receivers start flooding SFU with NACKs  for that same packets again and again and no RTXs are being sent at all which results in receiver ending up with a PLI request.
So whats going on is:
1. At some point packet loss spikes and RTX ratio exceeds 15%.
2. This results in `poll_packet_resend` always returning `None` because of [this](https://github.com/algesten/str0m/blob/35d9bbafa1f4a6146c09be87fdea8a94f5c58ae5/src/streams/send.rs#L545-L548)
3. Since no resends are made it never get to [this point](https://github.com/algesten/str0m/blob/35d9bbafa1f4a6146c09be87fdea8a94f5c58ae5/src/streams/send.rs#L573), …

Fix RTX stops working after packet loss spike

---

src/ice/agent.rs
src/ice/pair.rs
src/io/mod.rs
src/io/stun.rs

Currently, the `StunTiming` configuration gets copied into every new `CandidatePair` that is created. This means that changes to the timing configuration afterwards are not reflected in existing candidate pairs.
To fix this, we remove the `StunTiming` field from `CandidatePair` and instead pass in a reference everywhere where it is needed.
The usecase that I want to support with this is to allow lowering the frequency of STUN bindings in certain situations like idle connections. When a connection is not in use (i.e. there is no other traffic being sent over the UDP socket), detecting a failed connection isn't as time critical because the user isn't using the application. This allows the CPU to go to sleep and preserves battery on e.g. mobile devices.

refactor(ice): always use latest timing config

---

tests/common.rs
tests/srtp-replay-attack.rs

Simple testcase to duplicate incoming rtp packets to simulate a srtp replay attack.

SRTP replay attack test

---

src/session.rs
src/streams/receive.rs
src/streams/register.rs
src/streams/register_nack.rs

This is to protect str0m against SRTP replay attacks where already received packets are being repeated. Before this PR, this would force str0m to spend CPU decrypting it over and over again. With this PR, str0m checks the NACK register whether the packet is one we expect before doing the decryption.

Do not decrypt already received packets

---

src/crypto/dtls.rs
src/crypto/ossl/dtls.rs
src/crypto/ossl/stream.rs
src/dtls.rs
src/lib.rs

The openssl DTLS handshake does have internal timeouts that does resends. If we just poll the dtls subsystem, we will get resends. This PR adds a timeout during dtls handshake to poll for the resends.
* The built-in timer is 1 second with a backoff for each resend. This can be further configured, but the necessary functions are not exposed in the openssl crate.
* We can't test this because openssl notion of time is _real_ time. I don't see a way to pass in what the current time is.
Close #564

Timeouts during DTLS handshake

---

src/ice/agent.rs
src/ice/mod.rs

Candidates are redundant when their protocol and address are identical. When such a redundant candidate is added, `str0m` correctly either rejects the newly formed pair or replaces the existing one in case the priority is better.
However, new candidate pairs are still formed as part of looking for the remote candidate of an incoming STUN binding. In the presence of redundant candidates, whether we pick the correct one currently depends on in which order the original candidates have been added.
To make this deterministic and prevent the forming of new, redundant candidate pairs, we now explicitly pick the remote candidate with the highest priority.

fix(ice): match remote candidate of stun request by priority

---

CHANGELOG.md
src/change/direct.rs
src/change/sdp.rs
src/streams/mod.rs
src/streams/send.rs
tests/rtx-cache-0.rs

https://github.com/algesten/str0m/pull/566#issuecomment-2377171154
> Another thing is it would be great to be able to configure that `0.15` RTX cache drop ratio, mind if i do it in another PR? Probably as an additional argument to `StreamTx::set_rtx_cache`, so it will be `fn set_rtx_cache(&mut self, max_packets: usize, max_age: Duration, rtx_cache_drop_ratio: Option<f32>)` with `None` completely disabling this mechanic.

Configure RTX ratio cap

---

CHANGELOG.md
src/change/sdp.rs
src/session.rs
src/streams/send.rs

So I've been noticing that some receivers report `PeerStats.egress_loss_fraction` sitting at 20-40% with no other indications of packet loss,  and `MediaEgressStats.loss` reporting ~0%. Further investigation showed that it only happens with Firefox receivers cause Firefox does not support TWCC for audio m-lines. Example SDP:
```
v=0
o=mozilla...THIS_IS_SDPARTA-99.0 812743268998139128 0 IN IP4 0.0.0.0
...
a=sendrecv
a=extmap:1 urn:ietf:params:rtp-hdrext:ssrc-audio-level
a=extmap:2/recvonly urn:ietf:params:rtp-hdrext:csrc-audio-level
a=extmap:3 urn:ietf:params:rtp-hdrext:sdes:mid
...
a=sendrecv
a=extmap:3 urn:ietf:params:rtp-hdrext:sdes:mid
a=extmap:4 http://www.webrtc.org/experiments/rtp-hdrext/abs-send-time
a=extmap:5 urn:ietf:params:rtp-hdrext:toffset
a=extmap:6/recvonly …
```

Correctly handle per m-line TWCC

---

src/ice/agent.rs

The changes in `5c4c9d5` caused problems because we'd end up creating new identical pairs. For example, if an existing pair, `0-0`, exists as local: 192.168.1.33:5445, remote: 192.168.1.33:63461. Then, after processing a new offer another remote candidate would be added for 192.168.1.33:63461, call this pair `0-1`. When determining which pair an incoming binding request belonged too we'd then identify `0-1` instead of `0-0`(because `max_by_key`) returns the last value on ties. In Chrome this would work correctly, but in Firefox connectivity would be lost.
Ultimately adding a new remote candidate that is exactly the same as one that's already part of a viable pair is redundant, so we resolve this issue by simply skipping such candidates.

Dedupe remote ICE candidates

---

Cargo.toml

Some security requirements might be that a user must use system provided OpenSSL.
Added a new feature called openssl-vendored which uses openssl feature and also add the vendored flag.
Easy way to test if open ssl is vendored or not is to.
cargo tree | grep openssl-src -> vendored
changed default to be openssl-vendored to ensure no functionality change

Move openssl vendored featureflag to default

---

src/lib.rs
src/packet/bwe/arrival_group.rs
src/packet/bwe/delay_controller.rs
src/packet/bwe/loss_controller.rs
src/packet/bwe/macros.rs
src/packet/bwe/mod.rs
src/packet/bwe/rate_control.rs
src/packet/bwe/super_instant.rs
src/packet/bwe/trendline_estimator.rs
src/rtp/bandwidth.rs
src/rtp/rtcp/twcc.rs
src/session.rs

This PR, which resurrects #147, adds support for BWE based on loss. Prior to this the BWE system relied solely on congestion manifesting as increasing delay, but it can also manifest as loss, with this PR we'll also react to loss.
Like the existing delay based BWE this is based on goog_cc, in particular it's based on the commit `14e2779a6c` from last year. 
The fundamental problem with reacting to loss arising from congestion, is separating that loss from any inherent loss in the environment. For example, a peer might be using a poor WiFi with lots of packet loss on a downlink that can sustain, say 200Mbit/s. In such a situation we'd want to estimate their bandwidth at 200Mbit/s in the extreme, even if the inherent loss is 10%.
Simply reducing estimates based on observed packet loss does …

Add support for loss in BWE

---

src/packet/bwe/loss_controller.rs
src/packet/bwe/macros.rs

When loss limited, but increasing we shouldn't reset the loss limit
window, this prevents the recovery from happening.
This would cause estimates to get stuck in unrecoverable lows after big
spikes in loss.

Fix loss based BWE stuck in loss limited window

---

src/ice/agent.rs

We've recently had a bug in Firezone where we generated a lot of unnecessary server-reflexive candidates. This was only caught by chance due to a different bug report from a user.
We do have automated reporting set up whenever parts of our code emit `WARN` and `ERROR` logs. Adding a WARN log here allows this automated reporting to kick in if that should happen again.
I think - in general - adding a WARN log here is justified. Exceeding the max number of candidates can technically lead to connectivity problems so informing the user about this via a WARN log seems good.

chore: add warning log when exceeding max number of pairs

---

src/packet/h264.rs

One could fix and rewrite this in many ways, but to keep small changes this is my proposal.

Fix oob fuzz test failure

---

src/ice/pair.rs

fix: gracefully handle underflow when computing nomination time

---

src/change/direct.rs
src/change/sdp.rs
src/media/mod.rs
src/media/writer.rs
src/packet/pacer.rs
src/rtp/id.rs
src/rtp/mod.rs
src/session.rs
src/stats.rs
src/streams/mod.rs
src/streams/receive.rs
src/streams/send.rs

- **Move to MidRid instead of (Mid, Option<Rid>)**
- **Move MidRid to rtp/id**
- **Turn MidRid into a tuple**
- **Use MidRid in many more places**

Refactor internal tuple MidRid

---

CHANGELOG.md
src/rtp/rtcp/twcc.rs

Related to #605, #601
So while debugging related PR's I've noticed that sometimes, when reordering is present, packets that were previously reported as received (`TwccSendRecord.recv_report.remote_recv_time = Some`) were later rewritten as unreceived (`TwccSendRecord.recv_report.remote_recv_time =  None`) by TWCC that do not event include those previously acked packets. 
So I did a little debugging on how `Twcc.into_iter` works:
```
new TwccIter Twcc { sender_ssrc: Ssrc(1), ssrc: Ssrc(3003581636), base_seq: 1, status_count: 3, reference_time: 406753, feedback_count: 1, chunks: [VectorDouble(1280, 7)], delta: [Small(236), Small(1)] }
iterator return 1 NotReceived None
iterator return 2 ReceivedSmallDelta Some(Instant { tv_sec: 52064, tv_nsec: 454237868 })
iterator return 3 …
```

Limit TWCC iterator with packet status count

---

CHANGELOG.md
src/packet/bwe/mod.rs
src/rtp/rtcp/twcc.rs
src/session.rs

Fixes #599 
> The missing invariant here, at least as far as BWE is concerned, is that we don't want to process the same packet(as indicated by transport-cc sequence number) more than one time. We can achieve this either by apply_report to not return a range or, preferably, by changing send_records to only return "new" reports. Alternatively, and perhaps preferably, we add a new layer between TwccSendRegister and the BWE subsystem inspired by libWebRTC's TransportFeedbackAdapter construct as you suggest.
So here is a deduplicating adapter between `TwccSendRegister` and the insides of `SendSideBandwithEstimator`. It should do the job but looks kinda awkward to me. I would probably prefer encapsulating this inside of `TwccSendRegister` by simply removing `TwccSendRecord`s from the storage …

Dedupe acked packets from TwccSendRegister::apply_report()

---

examples/chat.rs
src/change/direct.rs
src/change/sdp.rs
src/lib.rs
src/media/event.rs
src/media/mod.rs
src/media/writer.rs
src/packet/pacer.rs
src/rtp/vla.rs
src/sdp/mod.rs
src/session.rs
src/streams/mod.rs
src/streams/send.rs
tests/bidirectional.rs
tests/contiguous.rs
tests/keyframes.rs
tests/remb.rs
tests/rtp-direct-mid-rid.rs
tests/rtx-cache-0.rs
tests/sdp-negotiation.rs
tests/stats.rs
tests/twcc.rs
tests/unidirectional-r-create-media.rs
tests/unidirectional.rs
tests/user-rtp-header-extension.rs

Adds support for specifying the RID when writing packets to str0m as well as for serialization of the VLA extended header.
There are a couple points that need to be resolved:
* Carrying the active/inactive state of streams from simulcast specification (adding the media) to when the SDP is created
* A couple of the VLA tests I wasn't sure about. Specifically the one that I did convert add the bidirectional serialization to (it says 3 active streams but it has no active spatial layers, which would end up being condensed to the shared bitmask)

Add simulcast sending support

---

src/change/sdp.rs
src/media/mod.rs

Fixes https://github.com/algesten/str0m/issues/611
https://github.com/algesten/str0m/commit/425a851a2de2d3af378c15b55d7e9ed16ca6a1b7 added a `From` impl that converted from a slice of RIDs into a `Rids` instance, and unconditionally used it when updating media via SDP. However, this impl did not take into account empty slices, which are naturally produced when simulcast is not in play. This caused non-simulcast tracks to start reporting `Rids::Specific(vec![])` once they were updated by e.g. a direction change.
As the correct `Rids` value on an empty slice depends on whether you're sending or receiving, this PR removes the `From` impl entirely and replaces it with manual conversion while updating media via SDP.

Fix RIDs bug on updating non-simulcast media

---

src/session.rs
src/streams/mod.rs
src/streams/send.rs
src/streams/send_stats.rs

See description in #610
Fixes #610
Fixes #613

Don't retain Receiver Report loss info when stats are disabled (take 2)

---

src/crypto/ossl/dtls.rs

Str0m cannot complete a DTLS handshake with a peer using a certificate signed with an secp384r1 key. The DTLS server hello indicates that that key is supported, however, Str0m (when using openssl) will reject fail the DTLS handshake. The issue is that Str0m is restricting OpenSSL to only use/accept the secp256r1 EC.
---- More details ----
set_tmp_ecdh() is deprecated in OpenSSL, and under the covers will call set_groups() with the EC group of the provided key. This restricts our session to the one given EC group (secp256r1/PRIME256V1 in the code) [See https://github.com/openssl/openssl/discussions/23070#discussioncomment-7885148]. This prevents session establishment with DTLS implementations using secp384r1 or another valid EC.
By simply removing the call, we are allowing OpenSSL to …

Remove restriction on EC to use on ECDH exchange

---

CHANGELOG.md
src/format.rs
src/sdp/data.rs
src/sdp/parser.rs

This PR adds AV1-specific parameters to `FormatParams` struct and `FormatParam` enum + parsing and serialization.

Support AV1-specific media format parameters

---

examples/chat.rs
examples/http-post.rs
src/ice/mod.rs
tests/common.rs

Rust 2024 treats `std::env::set_var` as unsafe function and it is possible to avoid it using direct log filter configuration API.

Avoid calls std::env::set_var to configure EnvFilter.

---

src/ice/agent.rs
src/io/stun.rs
src/lib.rs

In some situations, for example before TURN allocation it's not possible to construct a valid `MESSAGE-INTEGRITY` attribute, therefore we need to make this possible.
Designwise I've initially made the password optional on `to_bytes`, but an alternate approach that I prefer is
```rust
pub fn to_bytes(self, password: &str, buf: &mut [u8]) -> Result<usize, StunError> {
self.to_bytes_internal(Some(password), buf)
}
pub fn to_bytes_no_auth(buf: &mut [u8]) -> Result<usize, StunError> {
self.to_bytes_internal(Some(password), buf)
}
```
The detailed example section from the TURN RFC is useful as an example of the flow https://datatracker.ietf.org/doc/html/rfc5766#autoid-55

Optional integrity on STUN messages

---

src/media/mod.rs
src/media/writer.rs
src/packet/payload.rs
tests/unidirectional.rs

This is a proposal for implementing "start of talkspurt" support in the sample writer for use with DTX (Discontinuous Transmission) or silence suppression.
**Usage:**  
When running a client with str0m and using Opus with DTX enabled, the `start_of_talkspurt` (marker bit) should be set after periods of DTX. This indicates to the receiver that the next packet marks the beginning of a new talkspurt.
This signaling is important for jitter buffers, as it allows them to detect the end of silence periods and adjust their size accordingly.

Add start of talkspurt for sample writer

---

src/ice/agent.rs
src/ice/mod.rs

Follow-up to #640. Doing so uncovered a bug where we were still using `base` instead of `source_addr`.

refactor(ICE): improve same-IP-version preference test

---

src/ice/agent.rs

the motivation is to reduce ufrag collision in demuxer, allowing a very efficient simple lookup to find the related rtc instance.
16 characters because it matches with uuid4.
Google Meet uses even a larger ufrag of 28 chars, a=ice-ufrag:Ahc0x4S2M3Y5kQoKAAiKYigCIAEQ
I removed the Chrome comment, I'm not sure if this is still the case. The ICE transport connected just fine with Chrome. As mentioned above, Google Meet uses even a much large ufrag. I don't have any strong preference between 16 or 28 chars, as long as it's large enough to be most likely unique per SFU life.

increase ufrag length to 16

---

src/rtp/rtcp/twcc.rs
src/session.rs
src/stats.rs

Add RTT reporting at the `Rtc` level. This value will contain the most recent RTT based on TWCC feedback.

Add PeerStats::rtt

---

src/ice/agent.rs
src/ice/mod.rs
src/ice/pair.rs

In Firezone, we dynamically update the timing config of the `IceAgent` to move into a "low-power" mode when we are idling. As soon as we see packets that we need to tunnel, we reset the timing config to ensure we detect connectivity problems in a timely manner.
At present, str0m caches when it needs to next send a binding request and these caches are not cleared when the timing config changes. As such, it may take up to how ever long MAX RTO was set to before str0m actually sends another STUN binding.

fix(ice): bust cached timeout values on timing config change

---

CHANGELOG.md
examples/chat.rs
examples/http-post.rs
src/ice/agent.rs
src/ice/mod.rs
src/lib.rs
tests/bidirectional.rs
tests/common.rs
tests/contiguous.rs
tests/data-channel-direct.rs
tests/data-channel.rs
tests/flappy-ice-state.rs
tests/ice-restart.rs
tests/keyframes.rs
tests/mediatime-backwards.rs
tests/remb.rs
tests/stats.rs
tests/twcc.rs
tests/unidirectional-r-create-media.rs
tests/unidirectional.rs
tests/user-rtp-header-extension.rs

At present, `IceAgent::add_local_candidate` consumes the `Candidate` and returns a `bool` whether the candidate was accepted by the `IceAgent`. In most applications, one needs to test for this boolean to know, whether the candidate should be signaled to the remote party. For example, a redundant candidate doesn't need to be signaled to the remote.
The current API is sub-optimal for this usecase because one always needs to `clone` the candidate in order to have it available to sending it via the signalling layer. We therefore refactor this API to return an Option`` instead with a reference to the candidate if it got accepted.
In addition, as of #640, str0m has a feature where it computes the local preference of a `Candidate` such that relay candidates allocated via the same IP version are …

refactor(ice): return `Candidate` from `add_local_candidate`

---

src/packet/vp8.rs

I'm successfully using a GStreamer pipeline to send a VP8 encoded test pattern into str0m, but occasionally I'm seeing a `PacketError::ErrShortPacket` back from `Vp8Depacketizer.depacketize()`. Upon tracing the issue, I determined that the cause is a total packet length check at the top of the method, which I believe is incorrect.
According to the [VP8 Payload Descriptor documentation](https://datatracker.ietf.org/doc/html/rfc7741#section-4.2), there are two variations of this payload descriptor, with the more compact version only requiring a single octet. I regularly see valid packets in my tests with a length of less than four, which result in corrupted video when returned as an error instead of being processed.
I've recorded a short video demonstration of what I'm seeing with an …

Fix vp8 depacketize for small packets

---

src/lib.rs
src/packet/buffer_rx.rs
src/session.rs
tests/no-pre-ice-feedback.rs

Potential solution to https://github.com/algesten/str0m/issues/635.
Quite simply, it just clears any generated feedback if ICE has not yet been established. This prevents it from buffering indefinitely if ICE just never establishes at all.
I thought this might be a simpler solution than trying to have extra logic to gate generating that feedback in the first place.

Drop feedback until ICE is established

---

.github/workflows/cargo.yml
Cargo.lock
Cargo.toml
src/ice/agent.rs
src/ice/pair.rs
src/lib.rs
src/util/mod.rs
src/util/pii.rs
tests/pii.rs
wincrypto/Cargo.toml

**This is an opt-in feature flag and will be disabled by default to not change current behavior.**
It is important to be able to avoid logging PII (Personally Identifiable Information) because improper handling or exposure of such data can lead to privacy violations, regulatory penalties, reputational damage, and loss of customer trust.
IP is a clear example of PII, and this has been the focus of this PR. However there might be other information that we also want to put under PII such as ufrag, mids etc but that can be done in a follow up PR in an iterative manner.
- Introduced a new `Pii<T>` wrapper type in pii.rs that, when the `pii` feature is enabled, redacts sensitive values (shows `{REDACTED}` for `Display`/`Debug`).
- Updated logging throughout the codebase (notably in ICE and DTLS …

Pii newtype to redact pii data as feature

---

src/stats.rs
src/streams/receive.rs
src/streams/send.rs
src/streams/send_stats.rs

Fill in RemoteIngressStats, and RemoteEgressStats using the most recent RR or SR respectively.
I made the naming within the remote stats structs consistent with the local stats, so renamed "bytes_tx" to "bytes" .. since we don't differentiate that way in MediaIngressStats or MediaEgressStats.
Did not pass the ntp/rtp time values in the SR nor the last SR time + delay in RR. Not sure if we feel they're needed or not, figure they can be added when needed.

Add some remote stats from SR/RR stats into Ingress/EgressStats

---

src/ice/candidate.rs
src/ice/mod.rs

Relates to #663 
The ICE spec says that relay candidates should have their base set to the same as the relay address itself. This makes it impossible to preserve the behavior where the agent prefers to maintain IPv4/IPv6 between local address and relay. This needs a solution, but we are looking at a bigger refactor (see #663)

Remove base from relay candidates (follow spec)

---

CHANGELOG.md
src/ice/agent.rs
src/ice/candidate.rs
src/ice/mod.rs
src/ice/preference.rs
src/lib.rs

- **Candidate::local to track local interface**
- **Re-enable disabled tests**
- **Candidate::source_addr to use local instead of base**
- **Make local preference calculation pluggable**

Make local preference calculation pluggable

---

src/ice/agent.rs

It is possible that an ICE agent receives remote candidates prior to discovering its own local candidates. For example, if the agent roams networks and therefore clears all its local candidates, it first needs to e.g. communicate with TURN servers to learn its new host and server-reflexive candidates. The signalling layer may be quicker in sending across the remote candidates than the TURN servers are in responding to the STUN bindings.
In this case, `str0m` will currently report the connection immediately as "Disconnected" even though it hasn't even formed any pairs.
The code already contains a special-case for this where we don't disconnect if we don't have any remote candidates yet. The same reasoning given there is also true for the local candidates though. Therefore, we extend this …

fix(ice): don't disconnect if we are missing local candidates

---

CHANGELOG.md
src/ice/agent.rs

Firezone employs an idempotent signalling protocol where we don't do anything, if the ICE credentials are still the same. Currently, we decide this based on the local ICE credentials only but it would be better to also compare the remote ones. For this, the ICE agent should expose the remote credentials just like it exposes the local ones.

feat(ice): expose remote ICE credentials

---

Cargo.lock
Cargo.toml
src/ice/mod.rs

I was investigating our hole-punch behaviour with different NATs and thought it would be useful to have some tests in str0m that actually simulate different kinds of NATs to see what gets nominated.

test(ice): simulate port-restricted-cone and symmetric NATs

---

src/ice/mod.rs

In order to correctly associate the logs with the current agent, call `add_local_candidate` within the span of the `TestAgent`.

test(ice): add candidates inside agent's span

---

src/ice/agent.rs
src/ice/pair.rs

When debugging ICE connectivity, it is useful to know, which _kinds_ of candidates got nominated without having to trace back the indices the candidates are referring to. The candidate that a pair is referring to can change if it was first created through a peer-reflexive candidate. Hence, we need to make sure this "cache" is up-to-date every time we form pairs.
As an example, the output from one of our tests now looks like this:
```
2025-07-31T02:03:03.819285Z DEBUG R: str0m::ice_::agent: Created local peer reflexive candidate for mapped address: 6.6.6.6:1000
2025-07-31T02:03:03.819325Z DEBUG R: str0m::ice_::agent: Created peer reflexive remote candidate from STUN request: Candidate(prflx=5.5.5.5:62292/udp prio=1862270719)
2025-07-31T02:03:03.819332Z DEBUG R: str0m::ice_::agent: Created …
```

feat(ice): print candidate kind as part of pair

---

src/ice/pair.rs

A raw `Instant` isn't particularly useful because it is a platform-dependent implementation detail, what this `Instant` is relative to. Therefore, remove this from the debug output.

chore(ice): don't log last remote binding attempt time

---

CHANGELOG.md
src/format.rs
src/lib.rs
src/packet/buffer_rx.rs
src/packet/g7xx.rs
src/packet/mod.rs
src/rtp/mtime.rs

Adds support for PCMU and PCMA, payload types 0 and 8. I've written the bare minimum to make this functional and I'd be happy to flesh this out if desired.

Add PCM support

---

CHANGELOG.md
src/packet/bwe/trendline_estimator.rs

Fixes #698
So judging from the provided panic log:
```
Timing { remote_recv_time_ms: 2474.0, ...}, 
Timing { remote_recv_time_ms: 2583.0, ... }, 
...
Timing { remote_recv_time_ms:4273.0, ... }, 
Timing { remote_recv_time_ms: -151.75, ... }]
```
`Timing.remote_recv_time_ms` is a relative to the first value observed, it being negative means that this is an out-of-order sample with a `InterGroupDelayDelta.last_remote_recv_time` being less then `TrendlineEstimator.zero_time`. It being placed at the end breaks the monotonicity assert.

Fix InterGroupDelayDelta sorting in BWE TrendlineEstimator

---

src/io/stun.rs

If you craft a valid STUN packet, and only send the first 19bytes, you'll get a panic! since the check to match udp packet len to stun len subtracts 20 from the udp length, leading to underflow.

Fix panic! in stun.rs if crafted packet is small with.

---

CHANGELOG.md
src/change/direct.rs
src/dtls.rs
src/lib.rs
tests/common.rs
tests/data-channel-direct.rs

- Restores disabling DTLS remote fingerprint verification using `RtcConfig.set_fingerprint_verification`.
- closes #549 
- Fixes decoding username attribute of STUN message
- Sets the remote fingerprint on `Dtls` type handshake is completed

Restore disabling DTLS fingerprint verification, and decoding STUN username attribute
